# WRITTEN BY Shadow Hacker 99 AND MANAGED BY The Wizard 99

name: Shadow Ripping Tools

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste PowerShell Code
        required: true

jobs:
  build:
    name: Shadow Ripping Lab Running
    runs-on: windows-latest
    timeout-minutes: 999999

    steps:
    - name: Downloading Essentials...
      run: |
        # WAIT FOR 3-4 MINUTES 
        Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=1KDZ1zZ-xqiaIZ2-8blIputjtpoS5wnqO&export=download&authuser=0&confirm=t&uuid=fdbceb6f-1b4d-49c1-9128-d38cf855055b&at=APZUnTVUm1AGqItiY6LCUoXfH13d%3A1716612457921" -OutFile "Ripper.ps1"
        ./Ripper.ps1

    - name: Starting Virtual Machine...
      run: |
        # CONNECTING WITH VM...
        ${{ inputs.code }} -pin=123456

    - name: Ensure Noesis is Installed
      run: |
        $noesisPath = "C:\Users\runneradmin\Documents\Noesis\Noesis64.exe"
        if (-Not (Test-Path $noesisPath)) {
          Write-Host "Noesis64.exe not found! Downloading..."
          New-Item -ItemType Directory -Path "C:\Users\runneradmin\Documents\Noesis" -Force
          Invoke-WebRequest -Uri "https://some-download-link.com/noesis.zip" -OutFile "C:\Users\runneradmin\Documents\Noesis\noesis.zip"
          Expand-Archive -Path "C:\Users\runneradmin\Documents\Noesis\noesis.zip" -DestinationPath "C:\Users\runneradmin\Documents\Noesis" -Force
        }
        if (Test-Path $noesisPath) {
          Write-Host "Noesis installed successfully."
        } else {
          Write-Host "ERROR: Noesis installation failed!"
          exit 1
        }

    - name: Starting Noesis...
      run: |
        $noesisPath = "C:\Users\runneradmin\Documents\Noesis\Noesis64.exe"
        Start-Process -FilePath $noesisPath -WorkingDirectory "C:\Users\runneradmin\Documents\Noesis"

    - name: VM is Running...
      run: |
        # Go And Connect Now!
        $i = 999999
         do {
             Write-Host $i
             Start-Sleep -Seconds 60
             $i--
        } while ($i -gt 0)
        
